### ISSUE TITLE
Update office locations

### ISSUE THREAD

**Issue by kalongthewires** [b2io/base2.io#120]
Include both Columbus, OH and Pittsburgh, PA in our office locations.

Complexity: XS

**Comment by csteinert** [comment]
Copy file: https://docs.google.com/document/d/1gBmGnr3ZK1-FCWHnhg3ifHcMNEofXqqNvF1HhZdA4fg/edit#

**Comment by MLKendall** [comment]
I approve of this if we can leave open the option of adding We Are Here back in during the design process (at our discretion) 

PS - I love the line about satellites and the internet.

**Comment by tborres** [comment]
It's already been done

![image](https://user-images.githubusercontent.com/2048050/45712654-de8c7d80-bb5a-11e8-9071-939a4bbd97ab.png)
