### ISSUE TITLE
Logos for technologies

### ISSUE THREAD

**Issue by kalongthewires** [b2io/base2.io#154]
Dependencies: #153, #140 

Collect the logo images for the technologies listed in the document attached to #101.

**Comment by csteinert** [comment]
Figma doc is here: https://www.figma.com/file/fS5oOnTa798aWdEHYEanWeYb/tech_logos

**Comment by MLKendall** [comment]
Looks good - is there a separate logo for .NET Core, or it wrapped up in the .NET logo?

**Comment by csteinert** [comment]
.NET Core has been added!

**Comment by MLKendall** [comment]
Approved!
