### ISSUE TITLE
SEO testing

### ISSUE THREAD

**Issue by kalongthewires** [b2io/base2.io#166]
Determine what goal we want to be targeting for SEO optimization. What tooling can we put in place to gauge our level of search engine optimization currently and going forward? 

Potential tools:
- Front-end checklist: https://github.com/thedaviddias/Front-End-Checklist. 
- Lighthouse

**Comment by csteinert** [comment]
We will likely need:
- A meeting to determine what we're doing.
- A research card to find best tooling options.
- An implementation card.

**Comment by mpcondo** [comment]
Closing during process of backlog cleanup, this is an issue that will most likely be discussed under the scope of marketing.
