### ISSUE TITLE
Jobs

### ISSUE THREAD

**Issue by kalongthewires** [b2io/base2.io#175]
* Display job and apprenticeship information (same content as [the old Jobs page](https://github.com/b2io/base2.io/blob/2d551920abf4768c61075bfa589bcf7283be7db8/jobs/index.html)).
* Job application form
* Apprenticeship application form
* Send form information to the correct email recipient
* Thank you message on form submission
* Available on mobile and desktop.

**Comment by mpcondo** [comment]
Closing during backlog cleanup.  The jobs page has been updated, maintained, and used for recruiting several times.
