### ISSUE TITLE
Contact page header and background

### ISSUE THREAD

**Issue by kalongthewires** [b2io/base2.io#185]
* [x] Styles and markup for the Contact Us page header.
* [x] Display background image for Contact Us.
* [x] Implement Make Contact button.
* [x] Should work on mobile and desktop.
~* [ ] Purchase design assets listed in the design below.~

![image](https://user-images.githubusercontent.com/2043335/34174657-add25490-e4c7-11e7-9ce0-6e9d9219d492.png)

Design: https://www.figma.com/file/YApYHX8kQ0WI0i7NcxnrY2vL/BaseTwo-Contact-Page

**Comment by csteinert** [comment]
Moved purchasing line item to #204
