### ISSUE TITLE
Support target browsers

### ISSUE THREAD

**Issue by mewdriller** [b2io/base2.io#196]
- [x] Update the `babel-env` settings to make sure we're only transpiling the JS features that aren't supported by our target browsers.
- [x] Ensure that the `styled-components` prefixing (via `stylis`) is sufficient to support our target browsers.
- [x] Investigate CSS linting to avoid using features which aren't supported by our target browsers.

**Comment by csteinert** [comment]
We are going to support the following browsers:

### Desktop
IE: 11 and newer
Edge: (latest)
Chrome: (latest)
Safari: v10.1 and newer
Firefox: v52 and newer

### Mobile
**iOS** 
Safari: 10+
Chrome: (latest)

**Android**
Chrome: (latest)
