### ISSUE TITLE
Services content

### ISSUE THREAD

**Issue by kalongthewires** [b2io/base2.io#199]
Content for the services section of the website.

Update content for the Services section of the website in the Google document below only:

https://docs.google.com/a/base2.io/document/d/1vnc_ALc7RqoVFxaMk6Z7CPd94iw547pjsunbVlCwMRY/edit?usp=sharing

The content will be used as part of the design for the redesigned version of the website. Submit the Google Doc for PR as usual when content draft completed.

**Comment by MLKendall** [comment]
I think this is too minimalistic.  What is here would be good for headers, but I don't think there is enough information here to really let a new client understand what services we offer.  Especially if case studies are a little ways off, we need something so people have a idea of what we can actually do for them.
