### ISSUE TITLE
Smooth Scroll for Navigation

### ISSUE THREAD

**Issue by MLKendall** [b2io/base2.io#237]
Currently, the navigation jumps abruptly to a new section.  To create a better user experience, implement a smoother scroll to each of the individual sections.

- [x] Research the best method to implement a smooth scroll

- [ ] Implement the smooth scroll

- [ ] Test (include https://gist.github.com/csteinert/6c02cc6f17329c754e15fc4e2e762dc6 in PR)

https://css-tricks.com/smooth-scrolling-accessibility/

**Notes**
Current issues with the implementation (https://github.com/fisshy/react-scroll) (branch: 237-smooth-scroll):
- Scrolling links do not have proper hover cursor styles
- Global Nav uses the same markup on the Blog pages, but the scroll links only work if they're on the same page as the linked content (so you can't navigate back)
- The home page jumps back to the top any time the mobile nav panel is opened on small screens.

**Comment by csteinert** [comment]
https://css-tricks.com/smooth-scrolling-accessibility/

**Comment by csteinert** [comment]
Current issues with the implementation (https://github.com/fisshy/react-scroll) (branch: 237-smooth-scroll):
- Scrolling links do not have proper hover cursor styles
- Global Nav uses the same markup on the Blog pages, but the scroll links only work if they're on the same page as the linked content (so you can't navigate back)
- The home page jumps back to the top any time the mobile nav panel is opened on small screens.

**Comment by chriswhawkins** [comment]
I took a stab at this: https://github.com/b2io/base2.io/tree/237-smooth-scroll

It works fine when scrolling from the very top of the page and anytime you're scrolling up to a section.

**Comment by zachcd** [comment]
Jumping on this.

[] Make to top link a scroll instead of navigate
[] Implement smooth scroll
[] Add keyboard refocus

**Comment by zachcd** [comment]
I've tried a few packages now.  Issues with all of them.

https://www.npmjs.com/package/react-scrollable-anchor - Conflicts with styled-components

https://github.com/fisshy/react-scroll - Just a lot of issues and an old repo, not a good option now

https://github.com/Andarist/use-smooth-scroll - hooks but uses refs to find the target, doesn't work for cousin relationships between link and target

https://www.gatsbyjs.org/packages/gatsby-plugin-smoothscroll/ - conflicts with the current solution for mobile nav hiding, but could be solved, possible fallback

This is my current hope:
https://www.npmjs.com/package/react-anchor-link-smooth-scroll
Seems possible, but might have issues with navigating back to the main page on actual navigation links like jobs and blog.

**Comment by zachcd** [comment]
https://www.npmjs.com/package/smooth-scroll is working best.  Working on the easing now.
