### ISSUE TITLE
404 Design

### ISSUE THREAD

**Issue by MLKendall** [b2io/base2.io#241]
Create a Design for 404 Page
Designs should include both desktop + mobile

Design has already been started:
[https://www.figma.com/file/9YnauyzMvMchJZ6cdEAi3C/BaseTwo-404-Design](https://www.figma.com/file/9YnauyzMvMchJZ6cdEAi3C/BaseTwo-404-Design)

**Comment by csteinert** [comment]
Idea: Separate the cow and ufo into two SVGs and have them animate (wiggle) at slightly different speeds/directions.
