### ISSUE TITLE
Mobile Navigation Does Not Close After Link is Clicked

### ISSUE THREAD

**Issue by MLKendall** [b2io/base2.io#251]
The mobile navigation menu currently does not close after a link is clicked.  Scrolling to the top of the page reveals the still-open menu.  

Desired Behavior:  Navigation should close when a link is clicked (except for the phone and email buttons)

Devices Tested: iPhone SE, Google Pixel (original)

**Comment by csteinert** [comment]
Got some video of this bug:

![251-mobile-nav-issue](https://user-images.githubusercontent.com/1918353/36801006-e5760178-1c7e-11e8-8202-0ac0072c526e.gif)
