### ISSUE TITLE
Contact Section Text Does Not Render Well - iPhone

### ISSUE THREAD

**Issue by MLKendall** [b2io/base2.io#255]
Text in the Contact Section Appears to be Jagged on smaller screen sizes
Device Tested: iPhone SE

![img_2787](https://user-images.githubusercontent.com/1918353/36801890-43a14d82-1c81-11e8-9d22-596eef03ab39.jpg)

**Comment by csteinert** [comment]
Is the italic (+ narrow font weight) the issue here?

**Comment by mpcondo** [comment]
Closing Issue: 

I've tested this on multiple browsers with different sized windows, and two phones of different proportions and I am not able to replicate.
