### ISSUE TITLE
Mobile Navigation Buttons Covered by Bottom Menu

### ISSUE THREAD

**Issue by MLKendall** [b2io/base2.io#257]
The buttons at the bottom of the mobile navigation menu are covered by menus at the bottom of the screen in Safari and on Android.

Devices Tested: iPhone SE (Safari) and Google Pixel (Chrome)

**Comment by csteinert** [comment]
![img_2786](https://user-images.githubusercontent.com/1918353/36801775-fa6b3e52-1c80-11e8-8974-020bde8c74c4.PNG)
