### ISSUE TITLE
Satellite in Hero Moves when Scrolling

### ISSUE THREAD

**Issue by MLKendall** [b2io/base2.io#258]
The satellite starts out over the planet (incorrect position) and then moves when scrolling.

This is almost certainly due to the browser chrome sliding in and out.

- [ ] Test (include https://gist.github.com/csteinert/6c02cc6f17329c754e15fc4e2e762dc6 in PR)

Device Tested: iPhone SE

**Comment by csteinert** [comment]
![258-satellite-scroll-issue](https://user-images.githubusercontent.com/1918353/36801607-93e22ba0-1c80-11e8-8196-a8c4a7aebb0d.gif)

**Comment by kesslern** [comment]
I can't get the satellite to move with the iPhone SE, iPhone 11, or the device testing mode in Chrome's developer tools. I think this issue is not applicable anymore.

**Comment by mpcondo** [comment]
Closing Issue:

I tested this issue in multiple browsers with various window sizes, along with two different smartphones of different screen sizes and was unable to replicate this issue.  As @kesslern mentioned in his comment, I don't believe this to be a current issue.
