### ISSUE TITLE
Purchase Design Assets Before Release

### ISSUE THREAD

**Issue by MLKendall** [b2io/base2.io#276]
There are three more design assets which must be purchased before release of the website:

- [x] Space Background (https://www.freepik.com/free-vector/space-background_799476.htm)
- [x] Space Background with Planets (https://www.freepik.com/free-vector/space-background-with-planets_1229807.htm)

Both to be purchased (via one month Premium Subscription) from https://profile.freepik.com/payment/getstarted (Total: 9.99 for both)

- [x] Satellite by Mello Royalty-free SVG
(https://thenounproject.com/search/?q=Satellite&creator=2404951&i=1038948)
- [x] Writing by Hendra Sudibyo Royalty-free SVG
https://thenounproject.com/search/?q=Hand%20with%20Pen&i=1426461

Both to be purchase from The Noun Project ($1.99 each / Total: $3.98 for both)

**Comment by dmiller-nj** [comment]
The royalty-free SVGs are here:

[nouns.zip](https://github.com/b2io/base2.io/files/1790397/nouns.zip)

**Comment by dmiller-nj** [comment]
The Freepik subscription process fails at the last step when it comes back from Stripe. I can't get this done for now.

**Comment by mewdriller** [comment]
Here are the two SVGs from The Noun Project:

[nouns.zip](https://github.com/b2io/base2.io/files/1790441/nouns.zip)

**Comment by mewdriller** [comment]
The Freepik site's subscription system fails at the last step (when it comes back from Stripe). So I can't finish this process for now.
