### ISSUE TITLE
Site Does Not Scroll Once Navigation Item is Picked

### ISSUE THREAD

**Issue by MLKendall** [b2io/base2.io#282]
When a navigation item is chosen on mobile, you can no longer scroll the site.  The link also only goes to the designated section on second click of the nav button.

Device / Broswer Tested: iPhoneSE / Chrome.

**Comment by csteinert** [comment]
![282-scroll-issue](https://user-images.githubusercontent.com/1918353/37048175-14e4d8c4-213b-11e8-898b-e720a98e0aa4.gif)
