### ISSUE TITLE
feat(blog): Enable embedding iframes in blog posts.

### ISSUE THREAD

**Issue by csteinert** [b2io/base2.io#287]
As a user, I would like to be able to view embedded iframes (tweets, youtube videos, etc) in the site's blog posts.

We attempted to fix this in #239, and tried installing all manner of NPM plugins (eg https://www.npmjs.com/package/gatsby-remark-responsive-iframe) but couldn't get it to work and replaced the tweets and videos with text links.

**Comment by csteinert** [comment]
Full context: Tweets and YouTube video embeds are iframes, and without support for that element in markdown, we can't use those embeds.

**Comment by tborres** [comment]
It looks like scripts are also not being displayed. For instance the git-configured post (https://www.base2.io/2015/05/06/git-configured) should be displaying code via 

```html
<script src="http://gist-it.appspot.com/https://github.com/b2io/development-standards/blob/master/source-control/.gitconfig"></script>
```

But the code isn't displayed.
