### ISSUE TITLE
Blog background color

### ISSUE THREAD

**Issue by reeddunkle** [b2io/base2.io#297]
The blog page's background color is white when you navigate to it from the "Blog" nav button, but the background color is black when you load the URL directly.

![blog_white](https://user-images.githubusercontent.com/11543198/37598123-bba9dc42-2b57-11e8-8480-d8365d39ceb4.png)
----
![blog_black](https://user-images.githubusercontent.com/11543198/37598124-bcf83008-2b57-11e8-92c3-e5d9dfd41835.png)
----

To reproduce, click on the "Blog" nav button in the nav bar on the top. The background will be white. Then refresh the page and it will be black.

**Comment by csteinert** [comment]
Note: Individual posts do not seem to have this issue, only the main blog page
