### ISSUE TITLE
Blog mobile no scroll

### ISSUE THREAD

**Issue by reeddunkle** [b2io/base2.io#298]
On my phone, or using the Chrome dev tool's device emulator, when I navigate to the Blog page from the nav bar I'm unable to scroll (and the background is white).

If I reload the page, I can scroll (and the background is black).

Related: [#297 Blog background color](https://github.com/b2io/base2.io/issues/297).

**Comment by csteinert** [comment]
@reeddunkle What kind of phone do you have?
