### ISSUE TITLE
Create Join Our Team SVG

### ISSUE THREAD

**Issue by reeddunkle** [b2io/base2.io#335]
![join_our_team_svg](https://user-images.githubusercontent.com/11543198/46216761-4b97d400-c30e-11e8-867a-4f8b27316e17.PNG)

* https://www.figma.com/file/KFeaA4xNivQ7t9xvrNrjkQ/Jobs-For-Backlog?node-id=0%3A1

**Comment by tborres** [comment]
Per Caitlin, we can probably just do this with text and our logo
