### ISSUE TITLE
Purchase Design Assets

### ISSUE THREAD

**Issue by reeddunkle** [b2io/base2.io#336]
Get the blue astronaut 

![purchase_design_assets](https://user-images.githubusercontent.com/11543198/46216856-7e41cc80-c30e-11e8-929f-54531f4f7f81.PNG)

* https://www.figma.com/file/KFeaA4xNivQ7t9xvrNrjkQ/Jobs-For-Backlog?node-id=0%3A1

**Comment by chriswhawkins** [comment]
* [ ] Add assets to drive
https://drive.google.com/drive/u/0/folders/1ezDuH9-lJsY9RZYdJ05E7fKtGaqSoZbK
