### ISSUE TITLE
Blog code blocks

### ISSUE THREAD

**Issue by tborres** [b2io/base2.io#452]
The code blocks in blogs, such as the git-configured post, are not displaying

**Comment by zachcd** [comment]
Gatsby is clearing out the script tag that generates the gist.
`<script src="http://gist-it.appspot.com/https://github.com/b2io/development-standards/raw/master/source-control/.gitignore"></script>`

I think there're two options:
a. Use Gatsby code block syntax: https://www.gatsbyjs.org/docs/mdx/markdown-syntax/#code-blocks
    cons:
    no syntax highlighting
b. Create a Github Gist and use https://www.gatsbyjs.org/packages/gatsby-remark-embed-gist/
   cons:
   another import and some config

I'm going to go ahead with option B for now.

**Comment by zachcd** [comment]
There's not a reasonable solution to getting script tags through.  

Whether we include code in the blog markdown itself or use a gatsby plugin to fetch it, we will want something that can do prettifying and highlighting.  There's a few things to decide.  I'll be sticking on this.
