### ISSUE TITLE
Bug: Authorship missing on some blog pages 

### ISSUE THREAD

**Issue by k8hansen** [b2io/base2.io#479]
Some examples:

https://www.base2.io/2018/03/20/the-base-two-handbook
https://www.base2.io/2013/10/18/karma-tests-circle-ci

It appears as though authors are missing if they are no longer active employees.

**Comment by mewdriller** [comment]
It looks like we removed non-`active` team members from the `_content/team.json` file (and their associated profile pictures) in [this changeset](https://github.com/b2io/base2.io/commit/4ec94670da52e33c52092809d893c2f416dce609).
