### ISSUE TITLE
Enable Google Analytics and fix error

### ISSUE THREAD

**Issue by nelsW70** [b2io/base2.io#691]
This card is to re-evaluate the usage of Google Analytics.

GA code is commented out temporarily until error displayed in deployed site can be resolved

![Image](https://user-images.githubusercontent.com/17680907/266677147-242426a0-d6dc-45f3-9a01-c12910f54106.png)

**Comment by k8hansen** [comment]
unable to reproduce?

**Comment by k8hansen** [comment]
Unable to reproduce this error
