### ISSUE TITLE
Organize Components

### ISSUE THREAD

**Issue by mlam0527** [b2io/base2.io#722]
As a developer, I want to navigate the components folder with ease by organizing components to their respective pages.

**Acceptance Criteria**:
- Create a common folder for common components
- Organize layout/header/footer components into separate folder
   - This is similar to how the Approach Page, Battery Page etc. are laid out
- HomePage Folder
   - place pngs into new image folder (to follow current convention)

**Comment by nothingalike** [comment]
link to pages: https://drive.google.com/drive/u/1/folders/1aPzIHF3hVpFt33slmPE1EoxUYD5At4uV
