### ISSUE TITLE
console warning from react-scroll usage

### ISSUE THREAD

**Issue by nelsW70** [b2io/base2.io#772]
Clicking react-scroll link on Services page triggers console warning "Listener must be a named function" warning

**Comment by JaviAir** [comment]
Found this, the last two comments reference this same issue, no fix though

https://github.com/fisshy/react-scroll/pull/554

**Comment by laurapadilla** [comment]
I think that we might need to wrap the `Service` in the `Element` tag from react-scroll, since the issue is only happening in production I'm not sure how to test this.
