### ISSUE TITLE
Near perfect lighthouse score

### ISSUE THREAD

**Issue by JaviAir** [b2io/base2.io#799]
We need a near perfect score so potential clients or anyone who sees our site can be impressed or take us more seriously. 
Have our site give the impression of people who know what they're doing.

Desktop and Mobile

**Comment by laurapadilla** [comment]
Both SEO and Accessibility scores are 100

![Image](https://github.com/b2io/base2.io/assets/19558580/0a724199-cf11-47f3-84f9-445b85f67a35)
![Image](https://github.com/b2io/base2.io/assets/19558580/abe3e8a3-67d1-42c4-aa1a-66babc56f6b0)
