### ISSUE TITLE
Additional Costs checklist validation

### ISSUE THREAD

**Issue by mpcondo** [b2io/base2.io#863]
### **Summary**
 In the Additional Costs tab of Environmental, Quantity is a required field, but the UI that allows for the value to be empty

- Open Department Interfaces tab on an SE scope revision.
- Select Additional Costs tab, add Additional Cost, and fill out the form.
- Delete the value from the Quantity field
- The validation icon will still appear to pass

**Branching & Time Tracking**

- Branch off of `main`
- Track time to support

**Comment by tborres** [comment]
This was inadvertently added to the wrong repo, and has been moved to https://github.com/b2io/scopebuilder/issues/5400
