### ISSUE TITLE
Update content: Client list

### ISSUE THREAD

**Issue by tborres** [b2io/base2.io#93]
The clients listed on our website are fairly stale. It would be good to update these to reflect our latest clients.

* [ ] Remove Wendy's
* [ ] Remove Nature's One
* [ ] Remove rev1Ventures

Here's a few that we could consider, but we'll need to get permission

* [x] AEP (we have historical permission for this, and it's already on the website)
* [ ] NetJets
* [ ] Det Norske Veritas (DNV-GL)
* [ ] AC Lens
* [ ] Resource Ammirati / IBM
* [ ] BevQuery? 
* [ ] Quest4Cleanup?

Update in content document as well:
https://docs.google.com/a/base2.io/document/d/1yPEmKByTSslxJtNSxhWhghD5gO_f1YSQMpJAVXj79PU/edit?usp=sharing

Complexity: S

**Comment by csteinert** [comment]
Logos: https://www.figma.com/file/Y5UT3IRc3MfxhZIOnIe4UGZX/Client_Logos

**Comment by MLKendall** [comment]
Is Sherwin Williams represented somewhere here?  I seem to remember that was done through another company.

**Comment by csteinert** [comment]
Sherwin-Williams logo has been added to Figma, also added to "get permission" list.

**Comment by MLKendall** [comment]
This has my approval, don't know if anyone more familiar with the previous clients wants to take a second look or if it is good to go.

**Comment by csteinert** [comment]
Lots of folks have been involved in this card, so I think with your approval we're good to go. 😁
